config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index'
  get  'tasks/new', to: 'tasks#new', as: :new_task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#detail', as: :task
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy", as: :delete_task
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def detail
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/detail.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<% if @task.completed %>
        <p><i class="far fa-check-square"></i> - Task is completed</p>
      <% else %>
        <p><i class="far fa-square"></i> - Task is not complete</p>
      <% end %>

<p><%= link_to "Back to list", tasks_path %></p>
<p><%= link_to "Update list", edit_task_path %></p>

app/views/tasks/edit.html.erb
<h1>New Task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.check_box :completed %>
  <%= f.label :completed %>
  <%= f.submit "Update task"%>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

  <ul>
    <% @tasks.each do |task| %>
      <li>


       <% if task.completed %>
        <i class="far fa-check-square"></i>
      <% else %>
        <i class="far fa-square"></i>
      <% end %>

      <%= link_to task.title, task_path(task) %>
    </li>
    <%= link_to  delete_task_url(task), method: :delete, data: { confirm: "Are you sure?" } do %> <i class="far fa-trash-alt"></i>
    <% end %>
    <% end %>
  </ul>


<p><%= link_to "Add new task", new_task_path%></p>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.check_box :completed %>
  <%= f.submit "Create new task"%>
<% end %>